name: "Assignees4label"
on:
  issues:
    types: [labeled]

jobs:
  set-assignees:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: kyanagimoto/assignee4label@main
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        configuration-path: '.github/assignee4label.yml'
  slack_notification:
    if: github.event.issue.labels[0].name == 'definition_of_done'
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
    - uses: actions/checkout@v3
    - name: Notify Slack
      uses: edge/simple-slack-notify@master
      with:
        channel: '#testinvino'
        color: 'good'
        text: '@here There is a new blogpost idea from the development journey about ${{ github.event.issue.title }}. Check Productboard for more details https://datacite.productboard.com/feature-board/533790-development-journey-status ' 
        failure_text: 'Something went wrong.'
  
