name: Definition of Done Checklist Checker

on: issues

jobs:
  checkIssue:
    name: Check Issue for Incomplete Checklist
    if: github.event.issue.labels[0].name == 'definition_of_done'
    runs-on: ubuntu-latest
    steps:
      - uses: adamzolyak/checklist-checker-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
