name: Exit survey

on: 
  issues:
    types: [closed]

env:
  GITHUB_TOKEN: {{ secrets.ISSUES_TOKEN }}

jobs:
  surveySend:
    name: Exit survey
    runs-on: ubuntu-latest
    if: ${{ github.event.label.name == 'definition_of_done' }}
    steps:
      - uses: jdvr/action-add-comment@master
        with:
          comment: ':fireworks: Well done @{issue-assignees} this is a wrap! 
                    Could you fill this small retrospective survey https://forms.gle/tUrjLfRrhCB7uQg39.'
